### PR TITLE
[Discussion] Add French translation

### PR DESCRIPTION
**Pull request by 5bentz**
### Disclaimer: I'm a native French speaker.

@tuxor1337 
Could you keep the PR opened please? Maybe some *baguettes* will want to contribute :)

I have been quite liberal while translating and this PR made me dive into the English translation. Therefore, I propose some improvements to the English translation. (See PR #318)

---
#### Happy Easter!
There is a double-space `␣␣` somewhere in the German translation. Happy finding!

### CODE REVIEW

**Comment by 5bentz** [comment]
For translating, **vim/ex** comes in handy:

```
$ cat translation_en2fr.ex
:g/"message"/ s/password/mot de passe/
:g/"message"/ s/Copy/Copier/
:g/"message"/ s/Autofilling/Remplissage automatique/
:g/"message"/ s/Fill /Remplir /
:g/"message"/ s/fill /remplir /
:g/"message"/ s/Goto/Aller/
:g/"message"/ s/Display/Afficher/
:g/"message"/ s/submit/valider/
:g/"message"/ s/ and / et /
:g/"message"/ s/show /montrer /
:g/"message"/ s/Search/Chercher/
:g/"message"/ s/Refresh/Rafraîchir/
:g/"message"/ s/Preferences/Préférences/
:g/"message"/ s/New/Nouveau/
:g/"message"/ s/root/racine/
:g/"message"/ s/contextual/contextuel/
:g/"message"/ s/General/Général/
:g/"message"/ s/Fields/Champs/
:g/"message"/ s/Miscellaneous/Divers/
:g/"message"/ s/icon/icône/
:g/"message"/ s/login/identifiant/
:g/"message"/ s/Login/identifiant/
:g/"message"/ s///
:g/"message"/ s/Sorry, an unexpected error occurred/Désolé, une erreur inattendue est survenue/
:update
:quit

$ vim -E -s messages.json < ~/translation_en2fr.ex
```

**Comment by tuxor1337** [comment]
Thanks for the translation! Would you please include the new error messages from https://github.com/passff/passff/commit/e840cab141d43d21c613d3e7c3b6ff6d14406d11#diff-8f8a17eeb3eb8b6cc636fb8f10d5ae13 into your translation?

If you don't mind, I will merge your translation after that and submit a new PassFF version to AMO.

**Comment by 5bentz** [comment]
I will do it this evening.

**Comment by 5bentz** [comment]
Done. I force-pushed a single commit ;)

**Comment by 5bentz** [comment]
I tested this translation on Firefox 60 build 1 FR.
Everything seems alright. The toolbar menu prints the FR equivalents of *Display top-level* and *Display contextual* on two lines instead of one (because too long...). It looks OK.

**Pull request merged**
