### PR TITLE
make logging optional (toggle in preferences)

### LINKED ISSUE #297: passff prints debug information to browser console
Currently passff 1.1 prints debug information to FF's console, like this:

````
[PassFF] 8 matches for https://example.org
util.js:35:7
[PassFF] Best fit item example.org for https://example.org
util.js:35:7
[PassFF] Start pref-auto-fill
util.js:35:7
[PassFF] Start auto-fill using example.org undefined
util.js:35:7
[PassFF] Fill depth 0
````

This is a little annoying when doing web development, when we're looking at the console for other reasons.

#32 notes the same issue but it's from 2015.

Great work on this addon, thanks!

### PR DESCRIPTION
**Pull request by girst**
implements / fixes #297

* logging now disabled by default
* I do not know russian, so I haven't touched the `ru/` file. 

Side Note: when can we expect a new release (especially with the PR #281 merged)?

### CODE REVIEW

**Comment by tuxor1337** [comment]
Thanks!

Regarding the site note: I wanted to wait for some of the major Mac compatibility issues to settle before creating a new release: #267, #268 But since there's no sufficient feedback about those (and I don't have a Mac machine to test myself), there's no activity in this direction.

**Comment by girst** [comment]
thanks for the info. I'm really bugged by 281 and was hoping i could use it soon. :/

**Comment by tuxor1337** [comment]
You are free to use the latest version from GitHub by cloning the repository and calling `make VERSION=1.1a` from within the `/src` directory. Then you can install the file `/bin/1.1b/passff.xpi`.

**Comment by phryneas** [comment]
@tuxor: you could also make use of the firefox addon beta channel

**Comment by tuxor1337** [comment]
Thanks for the hint! I uploaded a new beta version (1.2b): https://addons.mozilla.org/de/firefox/addon/passff/versions/beta

**Pull request merged**
