### PR TITLE
Add locales: simplified chinese

### PR DESCRIPTION
**Pull request by ClarkQAQ**
Adds zh (simplified chinese) locale

### CODE REVIEW

**Comment by tuxor1337** [comment]
Thank you for your contribution!

Some of the strings are still in English. Are you planning to translate them as well, or would you prefer to merge this as is?

**Comment by ClarkQAQ** [comment]
> Thank you for your contribution!
> 
> Some of the strings are still in English. Are you planning to translate them as well, or would you prefer to merge this as is?

I will handle them in the next request shortly.

**Comment by ClarkQAQ** [comment]
> 感谢您的贡献！
> 
> 有些字符串仍然是英文的。 您是否也打算翻译它们，或者您更愿意按原样合并它们？

**Comment by ClarkQAQ** [comment]
> Thank you for your contribution!
> 
> Some of the strings are still in English. Are you planning to translate them as well, or would you prefer to merge this as is?

After a long time, I managed to find some time and completed all of the translation work.

**Comment by tuxor1337** [comment]
Great, thanks!

**Pull request merged**
